# Generated by Django 6.0.1 on 2026-01-22 02:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('ggr_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of GGR (Profit) to pay as commission.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ggr_payment_day', models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], default='0', help_text='Day of the week to process GGR commissions', max_length=15)),
                ('is_hybrid_active', models.BooleanField(default=False, help_text='Enable selection-based commission logic.')),
                ('enable_single_selection_override', models.BooleanField(default=False)),
                ('single_selection_calc_type', models.CharField(choices=[('percentage_stake', 'Percentage of Stake'), ('percentage_ggr', 'Percentage of GGR'), ('fixed_value', 'Fixed Value')], default='percentage_stake', max_length=20)),
                ('single_selection_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage or Fixed Amount', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkCommissionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_agent', 'Super Agent'), ('master_agent', 'Master Agent')], max_length=20, unique=True)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('payout_day_description', models.CharField(default='Last Friday', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CommissionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('period_type', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='AgentCommissionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_profile', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_agents', to='commission.commissionplan')),
            ],
        ),
        migrations.CreateModel(
            name='HybridCommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_selections', models.PositiveIntegerField()),
                ('max_selections', models.PositiveIntegerField(blank=True, help_text="Leave blank for 'and above'", null=True)),
                ('commission_percent', models.DecimalField(decimal_places=2, help_text='Percentage of Stake for this selection range', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hybrid_rules', to='commission.commissionplan')),
            ],
            options={
                'ordering': ['min_selections'],
                'unique_together': {('plan', 'min_selections')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyNetworkCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('downline_stake', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('downline_winnings', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('downline_paid_commissions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ngr', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_commissions', to='commission.commissionperiod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Network Commission',
                'verbose_name_plural': 'Monthly Network Commissions',
                'unique_together': {('user', 'period')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyAgentCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_stake', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_winnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ggr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_ggr_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_hybrid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_commissions', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_commissions', to='commission.commissionperiod')),
            ],
            options={
                'verbose_name': 'Weekly Agent Commission',
                'verbose_name_plural': 'Weekly Agent Commissions',
                'unique_together': {('agent', 'period')},
            },
        ),
    ]
