# Generated by Django 6.0.1 on 2026-01-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0013_result'),
        ('commission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailTransaction',
            fields=[
            ],
            options={
                'verbose_name': 'Retail Transaction',
                'verbose_name_plural': 'Retail Transactions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.user',),
        ),
        migrations.AddField(
            model_name='weeklyagentcommission',
            name='is_marked_for_payment',
            field=models.BooleanField(default=False, verbose_name='Pay Now?'),
        ),
        migrations.AlterField(
            model_name='weeklyagentcommission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
