# Generated by Django 5.2.10 on 2026-05-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0002_retailtransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidWeeklyAgentCommission',
            fields=[
            ],
            options={
                'verbose_name': 'Commission Paid',
                'verbose_name_plural': 'Commission Paid',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('commission.weeklyagentcommission',),
        ),
    ]
