# Generated by Django 5.2.10 on 2026-06-02 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _backfill_amount_paid(apps, schema_editor):
    WeeklyAgentCommission = apps.get_model('commission', 'WeeklyAgentCommission')
    MonthlyNetworkCommission = apps.get_model('commission', 'MonthlyNetworkCommission')

    WeeklyAgentCommission.objects.filter(status='paid', amount_paid=0).update(amount_paid=models.F('commission_total_amount'))
    MonthlyNetworkCommission.objects.filter(status='paid', amount_paid=0).update(amount_paid=models.F('commission_amount'))


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0004_agentcommissionprofile_assigned_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlynetworkcommission',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlynetworkcommission',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_commissions_paid_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlynetworkcommission',
            name='paid_from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_commissions_paid_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlynetworkcommission',
            name='paid_source',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='weeklyagentcommission',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='weeklyagentcommission',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_commissions_paid_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklyagentcommission',
            name='paid_from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_commissions_paid_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklyagentcommission',
            name='paid_source',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlynetworkcommission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyagentcommission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.RunPython(_backfill_amount_paid, _noop_reverse),
    ]
