# Generated by Django 5.2.10 on 2026-06-02 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0005_monthlynetworkcommission_amount_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRecall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recall_reason', models.CharField(choices=[('wrong_calculation', 'Wrong Calculation'), ('premature_payment', 'Premature Payment'), ('duplicate_payment', 'Duplicate Payment'), ('fraud_investigation', 'Fraud Investigation'), ('wrong_commission_profile', 'Wrong Commission Profile'), ('compliance_issue', 'Compliance Issue'), ('administrative_error', 'Administrative Error'), ('other', 'Other')], max_length=50)),
                ('other_reason_text', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('requested_by_role', models.CharField(blank=True, default='', max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('executed', 'Executed'), ('pending_approval', 'Pending Approval'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='executed', max_length=30)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_recalls', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_recalls_decided', to=settings.AUTH_USER_MODEL)),
                ('monthly_commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recall_requests', to='commission.monthlynetworkcommission')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_recalls', to='commission.commissionperiod')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_recalls_requested', to=settings.AUTH_USER_MODEL)),
                ('weekly_commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recall_requests', to='commission.weeklyagentcommission')),
            ],
            options={
                'ordering': ('-created_at',),
                'permissions': [('can_recall_commission', 'Can recall commission'), ('can_approve_commission_recall', 'Can approve commission recall')],
            },
        ),
        migrations.CreateModel(
            name='CommissionRecallApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_recall_approvals', to=settings.AUTH_USER_MODEL)),
                ('recall', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='commission.commissionrecall')),
            ],
            options={
                'ordering': ('-decided_at',),
            },
        ),
        migrations.CreateModel(
            name='CommissionRecallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_recalled', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recall_reason', models.CharField(choices=[('wrong_calculation', 'Wrong Calculation'), ('premature_payment', 'Premature Payment'), ('duplicate_payment', 'Duplicate Payment'), ('fraud_investigation', 'Fraud Investigation'), ('wrong_commission_profile', 'Wrong Commission Profile'), ('compliance_issue', 'Compliance Issue'), ('administrative_error', 'Administrative Error'), ('other', 'Other')], max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('recalled_by_role', models.CharField(blank=True, default='', max_length=30)),
                ('recall_date', models.DateField()),
                ('recall_time', models.TimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, default='', max_length=255)),
                ('old_status', models.CharField(blank=True, default='', max_length=30)),
                ('new_status', models.CharField(blank=True, default='', max_length=30)),
                ('old_amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('new_amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('old_total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('new_total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_recall_logs', to=settings.AUTH_USER_MODEL)),
                ('monthly_commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recall_logs', to='commission.monthlynetworkcommission')),
                ('recall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='commission.commissionrecall')),
                ('recalled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_recalls_executed', to=settings.AUTH_USER_MODEL)),
                ('weekly_commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recall_logs', to='commission.weeklyagentcommission')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
