# Generated by Django 5.2.10 on 2026-05-14 13:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('betting', '0055_alter_bettinglimitauditlog_action_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('is_vpn', models.BooleanField(db_index=True, default=False)),
                ('is_proxy', models.BooleanField(db_index=True, default=False)),
                ('is_tor', models.BooleanField(db_index=True, default=False)),
                ('is_datacenter', models.BooleanField(db_index=True, default=False)),
                ('risk_score', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPWhitelistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'IP Whitelist Entry',
                'verbose_name_plural': 'IP Whitelist Entries',
            },
        ),
        migrations.CreateModel(
            name='SyndicateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('risk_score', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArbitrageAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='betting.betticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('AUTO_SUSPEND_FIXTURE', 'Auto Suspend Fixture'), ('AUTO_SUSPEND_MARKET', 'Auto Suspend Market'), ('AUTO_SUSPEND_SELECTION', 'Auto Suspend Selection'), ('MANUAL_SUSPEND', 'Manual Suspend'), ('MANUAL_RESUME', 'Manual Resume'), ('OVERRIDE_SET', 'Override Set'), ('OVERRIDE_CLEARED', 'Override Cleared'), ('RISK_ALERT', 'Risk Alert')], db_index=True, max_length=40)),
                ('market_key', models.CharField(blank=True, default='', max_length=50)),
                ('selection_key', models.CharField(blank=True, default='', max_length=50)),
                ('message', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fixture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='betting.fixture')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskEngineSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_suspension_enabled', models.BooleanField(default=True)),
                ('max_fixture_liability', models.DecimalField(decimal_places=2, default=Decimal('20000000.00'), help_text='Auto-suspend fixture when projected payout liability exceeds this amount.', max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_market_liability', models.DecimalField(decimal_places=2, default=Decimal('10000000.00'), help_text='Auto-suspend market when projected payout liability exceeds this amount.', max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_selection_liability', models.DecimalField(decimal_places=2, default=Decimal('7000000.00'), help_text='Auto-suspend selection when projected payout liability exceeds this amount.', max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('risk_threshold_percent', models.DecimalField(decimal_places=2, default=Decimal('85.00'), help_text='0-100. Threshold used by risk scoring and alerting.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('deposit_reminder_threshold', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='If wallet balance is less than or equal to this amount, send deposit reminder notifications.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('rapid_bet_seconds', models.PositiveIntegerField(default=4, help_text='Flag rapid consecutive bet placements by the same user within this number of seconds.')),
                ('duplicate_ticket_window_seconds', models.PositiveIntegerField(default=90, help_text='Time window to treat tickets as potential duplicates (same signature).')),
                ('coordinated_window_seconds', models.PositiveIntegerField(default=60, help_text='Time window (seconds) for coordinated betting detection per IP/fingerprint.')),
                ('coordinated_threshold', models.PositiveIntegerField(default=5, help_text='If this many tickets on the same selection are detected in the coordinated window, flag as coordinated betting.')),
                ('late_bet_minutes', models.PositiveIntegerField(default=5, help_text='Flag late betting when a ticket is placed within this many minutes of kickoff.')),
                ('high_value_bet_amount', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), help_text='Flag a ticket as high-value when total stake is greater than or equal to this amount.', max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('vpn_proxy_detection_enabled', models.BooleanField(default=False)),
                ('vpn_proxy_block_betting', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_risk_engine_settings', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_risk_engine_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Risk Engine Settings',
                'verbose_name_plural': 'Risk Engine Settings',
            },
        ),
        migrations.CreateModel(
            name='SuspiciousActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DUPLICATE_TICKET', 'Duplicate Ticket'), ('RAPID_BETTING', 'Rapid Betting'), ('COORDINATED_BETTING', 'Coordinated Betting'), ('LATE_BETTING', 'Late Betting'), ('ODDS_TARGETING', 'Unusual Odds Targeting'), ('HIGH_ROI', 'High ROI'), ('ARBITRAGE', 'Arbitrage'), ('MULTI_ACCOUNTING', 'Multi Accounting')], db_index=True, max_length=40)),
                ('risk_score', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fingerprint_hash', models.CharField(blank=True, default='', max_length=128)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_logs', to='betting.betticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentExposureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_stake_today', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total_potential_payout_today', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('ticket_count_today', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_exposure_snapshot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['updated_at'], name='risk_agente_updated_852d75_idx')],
            },
        ),
        migrations.CreateModel(
            name='BettingPeriodLiabilitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_stake', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total_potential_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('net_exposure', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('ticket_count', models.PositiveIntegerField(default=0)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('betting_period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liability_snapshot', to='betting.bettingperiod')),
            ],
            options={
                'indexes': [models.Index(fields=['risk_score', 'updated_at'], name='risk_bettin_risk_sc_d8930a_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_hash', models.CharField(db_index=True, max_length=128)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('timezone_name', models.CharField(blank=True, default='', max_length=60)),
                ('screen', models.CharField(blank=True, default='', max_length=60)),
                ('platform', models.CharField(blank=True, default='', max_length=60)),
                ('language', models.CharField(blank=True, default='', max_length=40)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_fingerprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['fingerprint_hash', 'ip_address'], name='risk_device_fingerp_83de97_idx')],
            },
        ),
        migrations.CreateModel(
            name='DuplicateTicketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(db_index=True, max_length=128)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('fingerprint_hash', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='betting.betticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_ticket_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['signature', 'created_at'], name='risk_duplic_signatu_130800_idx')],
            },
        ),
        migrations.CreateModel(
            name='FixtureLiabilitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_stake', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total_potential_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('net_exposure', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('ticket_count', models.PositiveIntegerField(default=0)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('fixture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liability_snapshot', to='betting.fixture')),
            ],
            options={
                'indexes': [models.Index(fields=['risk_score', 'updated_at'], name='risk_fixtur_risk_sc_29e7a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='FixtureRiskState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_suspended', models.BooleanField(db_index=True, default=False)),
                ('suspension_reason', models.CharField(blank=True, default='', max_length=255)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('manual_override', models.BooleanField(default=False, help_text='If set, automated actions will not change this state.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_state', to='betting.fixture')),
                ('resumed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixture_resumptions', to=settings.AUTH_USER_MODEL)),
                ('suspended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixture_suspensions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['is_suspended', 'updated_at'], name='risk_fixtur_is_susp_ce84bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketLiabilitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_key', models.CharField(db_index=True, max_length=50)),
                ('total_stake', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total_potential_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('net_exposure', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('ticket_count', models.PositiveIntegerField(default=0)),
                ('exposure_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('last_ticket_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_liabilities', to='betting.fixture')),
            ],
            options={
                'indexes': [models.Index(fields=['fixture', 'market_key'], name='risk_market_fixture_48c679_idx'), models.Index(fields=['risk_score', 'updated_at'], name='risk_market_risk_sc_a4df43_idx')],
                'unique_together': {('fixture', 'market_key')},
            },
        ),
        migrations.CreateModel(
            name='MarketRiskState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_key', models.CharField(db_index=True, max_length=50)),
                ('is_suspended', models.BooleanField(db_index=True, default=False)),
                ('suspension_reason', models.CharField(blank=True, default='', max_length=255)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('manual_override', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_risk_states', to='betting.fixture')),
                ('resumed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_resumptions', to=settings.AUTH_USER_MODEL)),
                ('suspended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_suspensions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['fixture', 'market_key', 'is_suspended'], name='risk_market_fixture_ebd3dc_idx')],
                'unique_together': {('fixture', 'market_key')},
            },
        ),
        migrations.CreateModel(
            name='SelectionLiabilitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_key', models.CharField(db_index=True, max_length=50)),
                ('selection_key', models.CharField(db_index=True, max_length=50)),
                ('total_stake', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total_potential_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('ticket_count', models.PositiveIntegerField(default=0)),
                ('exposure_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('last_ticket_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_liabilities', to='betting.fixture')),
            ],
            options={
                'indexes': [models.Index(fields=['fixture', 'market_key', 'selection_key'], name='risk_select_fixture_3010c3_idx'), models.Index(fields=['risk_score', 'updated_at'], name='risk_select_risk_sc_31105c_idx')],
                'unique_together': {('fixture', 'market_key', 'selection_key')},
            },
        ),
        migrations.CreateModel(
            name='SelectionRiskState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_key', models.CharField(db_index=True, max_length=50)),
                ('selection_key', models.CharField(db_index=True, max_length=50)),
                ('is_suspended', models.BooleanField(db_index=True, default=False)),
                ('suspension_reason', models.CharField(blank=True, default='', max_length=255)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('manual_override', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_risk_states', to='betting.fixture')),
                ('resumed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selection_resumptions', to=settings.AUTH_USER_MODEL)),
                ('suspended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selection_suspensions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['fixture', 'market_key', 'selection_key', 'is_suspended'], name='risk_select_fixture_b618d7_idx')],
                'unique_together': {('fixture', 'market_key', 'selection_key')},
            },
        ),
        migrations.CreateModel(
            name='SharpBettorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_flagged', models.BooleanField(db_index=True, default=False)),
                ('win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('roi', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=9)),
                ('yield_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('avg_odds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_stake', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('ticket_count', models.PositiveIntegerField(default=0)),
                ('last_calculated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_sharp_bettors', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sharp_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['is_flagged', 'roi'], name='risk_sharpb_is_flag_019d0f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyndicateMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, default='', max_length=30)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='risk.syndicategroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syndicate_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['group', 'user'], name='risk_syndic_group_i_777160_idx')],
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserExposureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_stake_today', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total_potential_payout_today', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('ticket_count_today', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_exposure_snapshot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['updated_at'], name='risk_userex_updated_eccb3a_idx')],
            },
        ),
    ]
