# Generated by Django 5.2.2 on 2025-06-12 14:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BettingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Betting Periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('shop_address', models.CharField(blank=True, max_length=255, null=True)),
                ('user_type', models.CharField(choices=[('player', 'Player'), ('cashier', 'Cashier'), ('agent', 'Agent'), ('super_agent', 'Super Agent'), ('master_agent', 'Master Agent'), ('admin', 'Admin')], default='player', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('cashier_prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_under', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('master_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_agents_under', to=settings.AUTH_USER_MODEL)),
                ('super_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='super_agents_under', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='BetTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stake_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_odd', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('potential_winning', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_winning', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost'), ('cashed_out', 'Cashed Out'), ('deleted', 'Deleted'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_tickets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bet Tickets',
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_turnover', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_winnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ggr', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(limit_choices_to={'user_type__in': ['agent', 'super_agent', 'master_agent']}, on_delete=django.db.models.deletion.CASCADE, related_name='agent_payouts', to=settings.AUTH_USER_MODEL)),
                ('settled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_agent_payouts', to=settings.AUTH_USER_MODEL)),
                ('betting_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='betting.bettingperiod')),
            ],
            options={
                'verbose_name_plural': 'Agent Payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BonusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_selections', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('min_odd_per_selection', models.DecimalField(decimal_places=2, default=1.01, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))])),
                ('bonus_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name_plural': 'Bonus Rules',
                'unique_together': {('min_selections', 'min_odd_per_selection')},
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=255)),
                ('away_team', models.CharField(max_length=255)),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField()),
                ('home_win_odd', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))])),
                ('draw_odd', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))])),
                ('away_win_odd', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))])),
                ('over1_5_odd', models.DecimalField(decimal_places=2, default=Decimal('1.01'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))])),
                ('under1_5_odd', models.DecimalField(decimal_places=2, default=Decimal('1.01'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))])),
                ('over2_5_odd', models.DecimalField(decimal_places=2, default=Decimal('1.01'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))])),
                ('under2_5_odd', models.DecimalField(decimal_places=2, default=Decimal('1.01'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))])),
                ('over3_5_odd', models.DecimalField(decimal_places=2, default=Decimal('1.01'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))])),
                ('under3_5_odd', models.DecimalField(decimal_places=2, default=Decimal('1.01'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))])),
                ('btts_yes_odd', models.DecimalField(decimal_places=2, default=Decimal('1.01'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))])),
                ('btts_no_odd', models.DecimalField(decimal_places=2, default=Decimal('1.01'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))])),
                ('home_dnb_odd', models.DecimalField(decimal_places=2, default=Decimal('1.01'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))])),
                ('away_dnb_odd', models.DecimalField(decimal_places=2, default=Decimal('1.01'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('settled', 'Settled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, choices=[('home_win', 'Home Win'), ('draw', 'Draw'), ('away_win', 'Away Win'), ('over_1_5', 'Over 1.5 Goals'), ('under_1_5', 'Under 1.5 Goals'), ('over_2_5', 'Over 2.5 Goals'), ('under_2_5', 'Under 2.5 Goals'), ('over_3_5', 'Over 3.5 Goals'), ('under_3_5', 'Under 3.5 Goals'), ('btts_yes', 'Both Teams To Score - Yes'), ('btts_no', 'Both Teams To Score - No'), ('home_dnb', 'Home - Draw No Bet'), ('away_dnb', 'Away - Draw No Bet')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('betting_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='betting.bettingperiod')),
            ],
            options={
                'verbose_name_plural': 'Fixtures',
                'ordering': ['match_date', 'match_time'],
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(choices=[('home_win', 'Home Win'), ('draw', 'Draw'), ('away_win', 'Away Win'), ('over_1_5', 'Over 1.5 Goals'), ('under_1_5', 'Under 1.5 Goals'), ('over_2_5', 'Over 2.5 Goals'), ('under_2_5', 'Under 2.5 Goals'), ('over_3_5', 'Over 3.5 Goals'), ('under_3_5', 'Under 3.5 Goals'), ('btts_yes', 'Both Teams To Score - Yes'), ('btts_no', 'Both Teams To Score - No'), ('home_dnb', 'Home - Draw No Bet'), ('away_dnb', 'Away - Draw No Bet')], max_length=20)),
                ('odd_selected', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))])),
                ('is_winning_selection', models.BooleanField(blank=True, null=True)),
                ('bet_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_selections', to='betting.betticket')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='betting.fixture')),
            ],
            options={
                'verbose_name_plural': 'Selections',
            },
        ),
        migrations.AddField(
            model_name='betticket',
            name='selections',
            field=models.ManyToManyField(related_name='bet_tickets_selected', to='betting.selection'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('bet_placement', 'Bet Placement'), ('bet_payout', 'Bet Payout'), ('commission_payout', 'Commission Payout'), ('wallet_transfer_out', 'Wallet Transfer Out'), ('wallet_transfer_in', 'Wallet Transfer In'), ('bonus', 'Bonus'), ('ticket_deletion_refund', 'Ticket Deletion Refund'), ('withdrawal_refund', 'Withdrawal Refund')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_successful', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('initiating_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_transactions', to=settings.AUTH_USER_MODEL)),
                ('related_bet_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='betting.betticket')),
                ('related_payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='betting.agentpayout')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('bank_name', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('approved_rejected_time', models.DateTimeField(blank=True, null=True)),
                ('approved_rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_request', to='betting.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Withdrawals',
                'ordering': ['-request_time'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_withdrawal_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='betting.userwithdrawal'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('cashier_prefix__isnull', True), _negated=True), models.Q(('cashier_prefix', ''), _negated=True)), fields=('cashier_prefix',), name='unique_cashier_prefix_if_not_null_or_empty'),
        ),
        migrations.AlterUniqueTogether(
            name='agentpayout',
            unique_together={('agent', 'betting_period')},
        ),
        migrations.AlterUniqueTogether(
            name='fixture',
            unique_together={('betting_period', 'home_team', 'away_team', 'match_date')},
        ),
        migrations.AlterUniqueTogether(
            name='selection',
            unique_together={('bet_ticket', 'fixture')},
        ),
    ]
