# Generated by Django 6.0.1 on 2026-01-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_userwithdrawal_admin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
