# Generated by Django 6.0.1 on 2026-01-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_fixture_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
