# Generated by Django 6.0.1 on 2026-01-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0004_alter_fixture_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
