# Generated by Django 6.0.1 on 2026-01-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0005_transaction_paystack_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
