# Generated by Django 6.0.1 on 2026-01-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0006_activitylog_session_key_activitylog_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='betticket',
            name='ticket_id',
            field=models.CharField(editable=False, max_length=8, null=True, unique=True),
        ),
    ]
