# Generated by Django 6.0.1 on 2026-01-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0007_betticket_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='betticket',
            name='bet_type',
            field=models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple'), ('system', 'System')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='betticket',
            name='system_min_count',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum selections required for system bet (k in k/n)', null=True),
        ),
    ]
