# Generated by Django 6.0.1 on 2026-01-21 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0008_betticket_bet_type_betticket_system_min_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betticket',
            name='selections',
        ),
        migrations.AlterField(
            model_name='selection',
            name='bet_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='betting.betticket'),
        ),
    ]
