# Generated by Django 6.0.1 on 2026-01-21 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0009_remove_betticket_selections_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='bettingperiod',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='fixture',
            options={},
        ),
        migrations.AlterModelOptions(
            name='selection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='systemsetting',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userwithdrawal',
            options={},
        ),
        migrations.RenameField(
            model_name='systemsetting',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='fixture',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='selection',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='mac_address',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='userwithdrawal',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='userwithdrawal',
            name='transaction',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='serial_number',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled'), ('settled', 'Settled')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='selection',
            name='bet_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='selection',
            name='odd_selected',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='away_dnb_odd',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='away_win_odd',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='btts_no_odd',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='btts_yes_odd',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='draw_odd',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='home_dnb_odd',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='home_win_odd',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='over1_5_odd',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='over2_5_odd',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='over3_5_odd',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='result',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='under1_5_odd',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='under2_5_odd',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='under3_5_odd',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='updated_at',
        ),
    ]
