# Generated by Django 6.0.1 on 2026-01-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0011_alter_activitylog_user_alter_fixture_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='away_dnb_odd',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_win_odd',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='fixture',
            name='btts_no_odd',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='fixture',
            name='btts_yes_odd',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='fixture',
            name='draw_odd',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_dnb_odd',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_win_odd',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='fixture',
            name='over_1_5_odd',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='fixture',
            name='over_2_5_odd',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='fixture',
            name='over_3_5_odd',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='fixture',
            name='under_1_5_odd',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='fixture',
            name='under_2_5_odd',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='fixture',
            name='under_3_5_odd',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
