# Generated by Django 5.2.10 on 2026-01-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0014_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='navbar_color',
            field=models.CharField(default='#ffffff', help_text='Hex code (e.g., #ffffff) or color name', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='navbar_text_type',
            field=models.CharField(choices=[('dark', 'Light Text (for Dark Backgrounds)'), ('light', 'Dark Text (for Light Backgrounds)')], default='light', help_text="Choose 'Light Text' if using a dark navbar color, and vice versa.", max_length=10),
        ),
    ]
