# Generated by Django 5.2.6 on 2026-01-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0015_siteconfiguration_navbar_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='navbar_gradient_end',
            field=models.CharField(default='#f8f9fa', help_text='Gradient End Color (Right side)', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='navbar_gradient_start',
            field=models.CharField(default='#ffffff', help_text='Gradient Start Color (Left/Logo side)', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='navbar_link_hover_color',
            field=models.CharField(default='#007bff', help_text='Color of nav links on hover', max_length=50),
        ),
    ]
