# Generated by Django 5.2.6 on 2026-01-23 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0016_siteconfiguration_navbar_gradient_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='navbar_color',
        ),
    ]
