# Generated by Django 5.2.6 on 2026-01-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0017_remove_siteconfiguration_navbar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Upload a square image (e.g., .ico or .png) for the browser tab.', null=True, upload_to='site_branding/'),
        ),
    ]
