# Generated by Django 5.2.6 on 2026-01-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0019_alter_activitylog_options_activitylog_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='account_user_commission_authority',
            field=models.BooleanField(default=False, help_text='Enable or disable Account User commission authority.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='commission_payment_source',
            field=models.CharField(choices=[('system', 'System Default (Super Admin Wallet)'), ('account_wallet', 'Account User Wallet'), ('manual', 'Manual Selection Per Payout')], default='system', help_text='Select the funding source for commission payments.', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('bet_placement', 'Bet Placement'), ('bet_payout', 'Bet Payout'), ('commission_payout', 'Commission Payout'), ('wallet_transfer_out', 'Wallet Transfer Out'), ('wallet_transfer_in', 'Wallet Transfer In'), ('bonus', 'Bonus'), ('ticket_deletion_refund', 'Ticket Deletion Refund'), ('withdrawal_refund', 'Withdrawal Refund'), ('account_user_credit', 'Account User Credit'), ('account_user_debit', 'Account User Debit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('player', 'Player'), ('cashier', 'Cashier'), ('agent', 'Agent'), ('super_agent', 'Super Agent'), ('master_agent', 'Master Agent'), ('account_user', 'Account User'), ('admin', 'Admin')], default='player', max_length=20),
        ),
    ]
