# Generated by Django 5.2.6 on 2026-01-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0022_alter_activitylog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('player', 'Player'), ('cashier', 'Cashier'), ('agent', 'Agent'), ('super_agent', 'Super Agent'), ('master_agent', 'Master Agent'), ('account_user', 'Account User'), ('admin', 'Admin')], default='player', max_length=20),
        ),
    ]
