# Generated by Django 5.2.10 on 2026-01-26 08:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0023_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betticket',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='betticket',
            name='placed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='betticket',
            name='stake_amount',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='betticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost'), ('cashed_out', 'Cashed Out'), ('deleted', 'Deleted'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
