# Generated by Django 5.2.10 on 2026-01-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0024_alter_betticket_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Upload a favicon (small icon) for the browser tab.', null=True, upload_to='site_branding/'),
        ),
    ]
