# Generated by Django 5.2.10 on 2026-01-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0027_alter_user_options_user_updated_at_impersonationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='landing_page_background',
            field=models.ImageField(blank=True, help_text='Background image for the landing page', null=True, upload_to='site_branding/'),
        ),
    ]
