# Generated by Django 5.2.10 on 2026-02-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0028_siteconfiguration_landing_page_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_downline_wallets',
            field=models.BooleanField(default=True, help_text='Designates whether this agent can credit/debit downline wallets.'),
        ),
    ]
