# Generated by Django 5.2.10 on 2026-02-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0029_user_can_manage_downline_wallets'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedWithdrawal',
            fields=[
            ],
            options={
                'verbose_name': 'Processed Withdrawal',
                'verbose_name_plural': 'Processed Withdrawals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.userwithdrawal',),
        ),
        migrations.AddField(
            model_name='userwithdrawal',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userwithdrawal',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='User balance after withdrawal deduction', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userwithdrawal',
            name='balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='User balance before withdrawal deduction', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userwithdrawal',
            name='processed_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userwithdrawal',
            name='approved_rejected_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='userwithdrawal',
            name='request_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userwithdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20),
        ),
    ]
