# Generated by Django 5.2.10 on 2026-02-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0030_processedwithdrawal_userwithdrawal_admin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwithdrawal',
            name='approver_balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Approver's wallet balance after processing", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userwithdrawal',
            name='approver_balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Approver's wallet balance before processing", max_digits=12, null=True),
        ),
    ]
