# Generated by Django 5.2.10 on 2026-02-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0032_biometricauthlog_webauthncredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='serial_number',
            field=models.PositiveIntegerField(),
        ),
    ]
