# Generated by Django 5.2.10 on 2026-02-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0033_alter_fixture_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='account_user_commission_authority',
            field=models.BooleanField(default=False, help_text='Enable or disable Account User commission authority.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='commission_payment_source',
            field=models.CharField(choices=[('system', 'System Default (Super Admin Wallet)'), ('account_wallet', 'Account User Wallet'), ('manual', 'Manual Selection Per Payout')], default='system', help_text='Select the funding source for commission payments.', max_length=20),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled'), ('settled', 'Settled'), ('abandoned', 'Abandoned'), ('no_result', 'No Result')], default='scheduled', max_length=20),
        ),
    ]
