# Generated by Django 5.2.10 on 2026-02-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0034_siteconfiguration_account_user_commission_authority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='allow_double_bet',
            field=models.BooleanField(default=True, help_text='Allow users to place double bets (2 selections).'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='allow_multiple_bet',
            field=models.BooleanField(default=True, help_text='Allow users to place multiple bets (3 or more selections).'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='allow_single_bet',
            field=models.BooleanField(default=True, help_text='Allow users to place single bets (1 selection).'),
        ),
    ]
