# Generated by Django 5.2.10 on 2026-04-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0035_siteconfiguration_allow_double_bet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='background_color',
            field=models.CharField(default='#0a1a0a', help_text='Main background color', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='landing_page_player_image',
            field=models.ImageField(blank=True, help_text='Player image for the landing page', null=True, upload_to='site_branding/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='landing_page_sporty_image',
            field=models.ImageField(blank=True, help_text='Sporty image for the landing page', null=True, upload_to='site_branding/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='primary_color',
            field=models.CharField(default='#FFB800', help_text='Primary accent color (e.g. buttons)', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='secondary_color',
            field=models.CharField(default='#00FFFF', help_text='Secondary accent color (e.g. badges)', max_length=50),
        ),
    ]
