# Generated by Django 5.2.10 on 2026-04-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0036_siteconfiguration_background_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='landing_page_player_image',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='landing_page_sporty_image',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='secondary_color',
        ),
        migrations.AddField(
            model_name='transaction',
            name='external_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_gateway',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('monnify', 'Monnify'), ('kora', 'Kora')], default='paystack', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(default='StakeNaija', max_length=255),
        ),
    ]
