# Generated by Django 5.2.10 on 2026-04-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0037_remove_siteconfiguration_background_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('title', models.CharField(blank=True, help_text='Optional title for the image', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description for the image', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carousel Image',
                'verbose_name_plural': 'Carousel Images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='carousel_interval',
            field=models.PositiveIntegerField(default=5000, help_text='Carousel sliding interval in milliseconds (e.g., 5000 for 5 seconds).'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='show_ticket_status_on_landing',
            field=models.BooleanField(default=True, help_text="Show/Hide the 'Check Your Bet Ticket Status' section on the landing page."),
        ),
    ]
