# Generated by Django 5.2.10 on 2026-04-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0039_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetrequest',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='send_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
