# Generated by Django 5.2.10 on 2026-05-01 16:36

from django.db import migrations


def seed_footer_pages(apps, schema_editor):
    FooterPage = apps.get_model('betting', 'FooterPage')

    defaults = [
        ("our-company", "Our Company", "Our Company", 10),
        ("terms-and-conditions", "Terms & Conditions", "Terms & Conditions", 20),
        ("responsible-gaming", "Responsible Gaming", "Responsible Gaming", 30),
        ("privacy-policy", "Privacy Policy", "Privacy Policy", 40),
        ("contact-us", "Contact Us", "Contact Us", 50),
        ("betting-rules", "Betting Rules", "Betting Rules", 60),
        ("ndpr", "NDPR", "NDPR", 70),
        ("ndpc", "NDPC", "NDPC", 80),
    ]

    for slug, footer_label, title, order in defaults:
        FooterPage.objects.get_or_create(
            slug=slug,
            defaults={
                "footer_label": footer_label,
                "title": title,
                "order": order,
                "is_active": True,
                "show_in_footer": True,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ('betting', '0043_footerbadge_footerpage'),
    ]

    operations = [
        migrations.RunPython(seed_footer_pages, migrations.RunPython.noop),
    ]

