# Generated by Django 5.2.10 on 2026-05-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0044_seed_footer_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerbadge',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
