# Generated by Django 5.2.10 on 2026-05-01 16:50

import hashlib

from django.db import migrations


def backfill_footerbadge_hash(apps, schema_editor):
    FooterBadge = apps.get_model('betting', 'FooterBadge')

    for b in FooterBadge.objects.all().iterator():
        if not getattr(b, 'image', None) or getattr(b, 'content_hash', ''):
            continue
        try:
            b.image.open('rb')
            h = hashlib.sha256()
            for chunk in iter(lambda: b.image.read(8192), b''):
                h.update(chunk)
            b.content_hash = h.hexdigest()
        finally:
            try:
                b.image.close()
            except Exception:
                pass
        b.save(update_fields=['content_hash'])


class Migration(migrations.Migration):
    dependencies = [
        ('betting', '0045_footerbadge_content_hash'),
    ]

    operations = [
        migrations.RunPython(backfill_footerbadge_hash, migrations.RunPython.noop),
    ]

