# Generated by Django 5.2.10 on 2026-05-01 17:10

from django.db import migrations


def remove_sample_footer_badges(apps, schema_editor):
    FooterBadge = apps.get_model('betting', 'FooterBadge')

    sample_names = [
        'footer_badges/mastercard.png',
        'footer_badges/interswitch.png',
        'footer_badges/flutterwave.png',
        'footer_badges/monnify.png',
        'footer_badges/paystack.png',
        'footer_badges/opay.png',
    ]

    FooterBadge.objects.filter(image__in=sample_names, alt_text='', link_url='').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('betting', '0046_backfill_footerbadge_hash'),
    ]

    operations = [
        migrations.RunPython(remove_sample_footer_badges, migrations.RunPython.noop),
    ]

