# Generated by Django 5.2.10 on 2026-05-01 17:14

from django.db import migrations


def remove_footer_badge_strip_hash(apps, schema_editor):
    FooterBadge = apps.get_model('betting', 'FooterBadge')

    strip_hash = '1d9400254d7db05c0114055b5b605edcd513c800b42a39b9f90b416929c508c7'
    FooterBadge.objects.filter(content_hash=strip_hash, alt_text='', link_url='').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('betting', '0047_remove_sample_footer_badges'),
    ]

    operations = [
        migrations.RunPython(remove_footer_badge_strip_hash, migrations.RunPython.noop),
    ]

