# Generated by Django 5.2.10 on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("betting", "0048_remove_footer_badge_strip_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="withdrawal_pin",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="user",
            name="withdrawal_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="withdrawal_locked",
            field=models.BooleanField(default=False),
        ),
    ]

