# Generated by Django 5.2.10 on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("betting", "0049_user_withdrawal_pin_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="withdrawal_locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

