# Generated by Django 5.2.10 on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("betting", "0050_user_withdrawal_locked_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bank_account_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]

