# Generated by Django 5.2.10 on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("betting", "0051_user_bank_account_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="downline_activity_last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

