# Generated by Django 5.2.10 on 2026-05-13 11:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0052_user_downline_activity_last_seen_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonusrule',
            options={'ordering': ['min_selections', 'max_selections', 'min_odd_per_selection'], 'verbose_name_plural': 'Bonus Rules'},
        ),
        migrations.AlterUniqueTogether(
            name='bonusrule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='betticket',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='betticket',
            name='bonus_applied_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='betticket',
            name='bonus_base',
            field=models.CharField(choices=[('gross', 'Gross Winnings (Total Return)'), ('net', 'Net Winnings (Return - Stake)')], default='gross', max_length=10),
        ),
        migrations.AddField(
            model_name='betticket',
            name='bonus_base_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='betticket',
            name='bonus_is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='betticket',
            name='bonus_percentage_applied',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
        ),
        migrations.AddField(
            model_name='betticket',
            name='bonus_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='betting.bonusrule'),
        ),
        migrations.AddField(
            model_name='betticket',
            name='original_selections_count',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='betticket',
            name='payout_processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='betticket',
            name='placed_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bonusrule',
            name='allow_accumulator_bets',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bonusrule',
            name='allow_single_bets',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bonusrule',
            name='allow_system_bets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bonusrule',
            name='bonus_base',
            field=models.CharField(choices=[('gross', 'Gross Winnings (Total Return)'), ('net', 'Net Winnings (Return - Stake)')], default='gross', max_length=10),
        ),
        migrations.AddField(
            model_name='bonusrule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bonusrule',
            name='max_bonus_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='bonusrule',
            name='max_selections',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bonusrule',
            name='bonus_percentage',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
        ),
        migrations.AlterField(
            model_name='bonusrule',
            name='min_odd_per_selection',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.01'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))]),
        ),
        migrations.AlterField(
            model_name='bonusrule',
            name='min_selections',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
