# Generated by Django 5.2.10 on 2026-05-13 14:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0053_alter_bonusrule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='betticket',
            name='betting_limits_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='AgentBettingLimitOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('custom_limits_enabled', models.BooleanField(default=True)),
                ('min_stake', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_stake', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_winning', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_odds_per_ticket', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_stake_by_ticket_type', models.JSONField(blank=True, default=dict)),
                ('max_winning_by_ticket_type', models.JSONField(blank=True, default=dict)),
                ('max_selections_per_ticket', models.PositiveIntegerField(blank=True, null=True)),
                ('max_payout_per_agent_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_payout_per_user_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(limit_choices_to={'user_type__in': ['agent', 'super_agent', 'master_agent']}, on_delete=django.db.models.deletion.CASCADE, related_name='betting_limit_override', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agent_betting_overrides', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_agent_betting_overrides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BettingLimitAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('GLOBAL_UPDATE', 'Global Update'), ('AGENT_UPDATE', 'Agent Update'), ('TICKET_REJECTED', 'Ticket Rejected')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='betting_limit_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('affected_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='betting_limit_audit_affected_user', to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['agent', 'super_agent', 'master_agent']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='betting_limit_audit_agent', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='betting_limit_audit_logs', to='betting.betticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalBettingSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('betting_enabled', models.BooleanField(default=True)),
                ('min_stake', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_stake', models.DecimalField(decimal_places=2, default=Decimal('500000.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_winning', models.DecimalField(decimal_places=2, default=Decimal('40000000.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_stake_by_ticket_type', models.JSONField(blank=True, default=dict)),
                ('max_winning_by_ticket_type', models.JSONField(blank=True, default=dict)),
                ('max_odds_per_ticket', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_selections_per_ticket', models.PositiveIntegerField(blank=True, null=True)),
                ('max_payout_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_payout_per_user_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_global_betting_settings', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_global_betting_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
