# Generated by Django 5.2.10 on 2026-05-14 13:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0054_betticket_betting_limits_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bettinglimitauditlog',
            name='action_type',
            field=models.CharField(choices=[('GLOBAL_UPDATE', 'Global Update'), ('AGENT_UPDATE', 'Agent Update'), ('USER_UPDATE', 'User Update'), ('TICKET_REJECTED', 'Ticket Rejected')], max_length=30),
        ),
        migrations.CreateModel(
            name='UserBettingLimitOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('custom_limits_enabled', models.BooleanField(default=True)),
                ('min_stake', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_stake', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_winning', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_odds_per_ticket', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_stake_by_ticket_type', models.JSONField(blank=True, default=dict)),
                ('max_winning_by_ticket_type', models.JSONField(blank=True, default=dict)),
                ('max_selections_per_ticket', models.PositiveIntegerField(blank=True, null=True)),
                ('max_payout_per_user_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_user_betting_overrides', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_user_betting_overrides', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_betting_limit_override', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
