# Generated by Django 5.2.10 on 2026-05-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0055_alter_bettinglimitauditlog_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='betticket',
            name='min_winning',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
