# Generated by Django 5.2.10 on 2026-05-22 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0056_betticket_min_winning'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayDeposit',
            fields=[
            ],
            options={
                'verbose_name': 'Payment Gateway Deposit',
                'verbose_name_plural': 'Payment Gateway Deposit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.transaction',),
        ),
        migrations.CreateModel(
            name='CashierRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('other_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('cashier_code', models.CharField(max_length=10)),
                ('cashier_email', models.EmailField(max_length=254)),
                ('cashier_username', models.CharField(max_length=50)),
                ('cashier_prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(limit_choices_to={'user_type': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='cashier_registration_requests', to=settings.AUTH_USER_MODEL)),
                ('created_cashier', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_cashier_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovedNewCashier',
            fields=[
            ],
            options={
                'verbose_name': 'Approved New Cashier',
                'verbose_name_plural': 'Approved New Cashier',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.cashierregistrationrequest',),
        ),
        migrations.CreateModel(
            name='PendingCashierRegistration',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Cashier Registration',
                'verbose_name_plural': 'Pending Cashier Registration',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.cashierregistrationrequest',),
        ),
        migrations.AddConstraint(
            model_name='cashierregistrationrequest',
            constraint=models.UniqueConstraint(fields=('cashier_email',), name='unique_cashier_request_email'),
        ),
        migrations.AddConstraint(
            model_name='cashierregistrationrequest',
            constraint=models.UniqueConstraint(fields=('agent', 'cashier_code'), name='unique_cashier_request_agent_code'),
        ),
    ]
