# Generated by Django 5.2.10 on 2026-05-23 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0057_paymentgatewaydeposit_cashierregistrationrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='betting_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections', to='betting.bettingperiod'),
        ),
        migrations.AddField(
            model_name='selection',
            name='fixture_away_team',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='selection',
            name='fixture_home_team',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='selection',
            name='fixture_match_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selection',
            name='fixture_match_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selection',
            name='fixture_serial_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='selection',
            name='fixture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections', to='betting.fixture'),
        ),
    ]
