# Generated by Django 5.2.10 on 2026-05-23 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0058_selection_fixture_setnull_snapshot'),
        ('pending_registration', '0002_registered_by_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crm_role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('ops', 'Ops'), ('compliance', 'Compliance'), ('supervisor', 'Supervisor')], db_index=True, default='viewer', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('player', 'Player'), ('cashier', 'Cashier'), ('agent', 'Agent'), ('super_agent', 'Super Agent'), ('master_agent', 'Master Agent'), ('account_user', 'Account User'), ('crm', 'CRM'), ('admin', 'Admin')], default='player', max_length=20),
        ),
        migrations.CreateModel(
            name='CRMActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('WITHDRAWAL_APPROVED', 'Withdrawal Approved'), ('WITHDRAWAL_REJECTED', 'Withdrawal Rejected'), ('USER_SUSPENDED', 'User Suspended'), ('USER_UNSUSPENDED', 'User Unsuspended'), ('PROFILE_EDITED', 'Profile Edited'), ('CASHIER_REG_APPROVED', 'Cashier Registration Approved'), ('CASHIER_REG_REJECTED', 'Cashier Registration Rejected'), ('AGENT_REG_APPROVED', 'Agent Registration Approved'), ('AGENT_REG_REJECTED', 'Agent Registration Rejected')], db_index=True, max_length=50)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_actions', to=settings.AUTH_USER_MODEL)),
                ('cashier_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_actions', to='betting.cashierregistrationrequest')),
                ('pending_agent_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_actions', to='pending_registration.pendingagentregistration')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_action_targets', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_actions', to='betting.betticket')),
                ('withdrawal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_actions', to='betting.userwithdrawal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
