# Generated by Django 5.2.10 on 2026-05-24 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0061_alter_crmactionlog_action_type_alter_user_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='finance_role',
            field=models.CharField(blank=True, choices=[('manager', 'Finance Manager'), ('accountant', 'Accountant'), ('auditor', 'Auditor'), ('settlement', 'Settlement Officer'), ('withdrawal', 'Withdrawal Officer')], db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('player', 'Player'), ('cashier', 'Cashier'), ('agent', 'Agent'), ('super_agent', 'Super Agent'), ('master_agent', 'Master Agent'), ('retail_manager', 'Retail Manager'), ('finance', 'Finance'), ('account_user', 'Account User'), ('crm', 'CRM'), ('admin', 'Admin')], default='player', max_length=20),
        ),
        migrations.CreateModel(
            name='FinanceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('WITHDRAWAL_APPROVED', 'Withdrawal Approved'), ('WITHDRAWAL_REJECTED', 'Withdrawal Rejected'), ('TX_REVERSED', 'Transaction Reversed'), ('TX_VERIFIED', 'Transaction Verified'), ('WALLET_ADJUSTED', 'Wallet Adjusted'), ('REPORT_EXPORTED', 'Report Exported')], db_index=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_action_targets', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_audit_logs', to='betting.transaction')),
                ('withdrawal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_audit_logs', to='betting.userwithdrawal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
