# Generated by Django 5.2.10 on 2026-05-24 22:30

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_default_ledger_accounts(apps, schema_editor):
    LedgerAccount = apps.get_model('betting', 'LedgerAccount')
    defaults = [
        ('CASH_OPS', 'Operational Cash', 'asset'),
        ('LIAB_WALLET', 'Wallet Liabilities', 'liability'),
        ('REV_GGR', 'Betting Revenue (GGR)', 'revenue'),
        ('EXP_PAYOUTS', 'Payouts Expense', 'expense'),
        ('EXP_BONUS', 'Bonus Expense', 'expense'),
        ('EXP_COMM', 'Commission Expense', 'expense'),
        ('EXP_GATEWAY', 'Payment Gateway Fees', 'expense'),
        ('EQUITY_SUSPENSE', 'Suspense / Adjustments', 'equity'),
    ]
    for code, name, account_type in defaults:
        LedgerAccount.objects.get_or_create(
            code=code,
            defaults={'name': name, 'account_type': account_type, 'is_active': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0003_paidweeklyagentcommission'),
        ('betting', '0062_user_finance_role_alter_user_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSettlementBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('settlement_type', models.CharField(choices=[('weekly_commission', 'Weekly Commissions'), ('network_commission', 'Network Commissions'), ('mixed_commission', 'Mixed Commissions'), ('manual', 'Manual')], db_index=True, max_length=30)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_settlement_batches_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_settlement_batches_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], db_index=True, max_length=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(db_index=True)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries_created', to=settings.AUTH_USER_MODEL)),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='betting.transaction')),
                ('related_withdrawal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='betting.userwithdrawal')),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('paystack', 'Paystack'), ('monnify', 'Monnify'), ('kora', 'Korapay')], db_index=True, max_length=20)),
                ('event_type', models.CharField(choices=[('init', 'Initialize'), ('verify', 'Verify'), ('webhook', 'Webhook'), ('reconcile', 'Reconcile')], db_index=True, max_length=20)),
                ('reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_events', to='betting.transaction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalPinVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_pin_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceTransactionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('flagged', 'Flagged'), ('rejected', 'Rejected')], db_index=True, max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transaction_reviews', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_reviews', to='betting.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='betting.ledgeraccount')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='betting.journalentry')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceSettlementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('agent_payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_settlement_items', to='betting.agentpayout')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='betting.financesettlementbatch')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_settlement_items', to=settings.AUTH_USER_MODEL)),
                ('monthly_commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_settlement_items', to='commission.monthlynetworkcommission')),
                ('weekly_commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_settlement_items', to='commission.weeklyagentcommission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(seed_default_ledger_accounts, migrations.RunPython.noop),
    ]

