# Generated by Django 5.2.10 on 2026-05-24 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0063_finance_settlements_ledger_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledFinanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('dataset', models.CharField(choices=[('transactions', 'Transactions'), ('deposits', 'Deposits'), ('withdrawals', 'Withdrawals'), ('ledger', 'Finance Audit Ledger'), ('journals', 'Journal Entries'), ('settlements', 'Settlements'), ('gateway_logs', 'Gateway Logs'), ('pin_logs', 'Withdrawal PIN Logs')], db_index=True, max_length=30)),
                ('report_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('pdf', 'PDF')], default='csv', max_length=10)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], db_index=True, default='daily', max_length=10)),
                ('recipients', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_status', models.CharField(blank=True, default='', max_length=20)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_finance_reports_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]

