# Generated by Django 5.2.10 on 2026-05-24 22:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0064_scheduledfinancereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeauditlog',
            name='action_type',
            field=models.CharField(choices=[('WITHDRAWAL_APPROVED', 'Withdrawal Approved'), ('WITHDRAWAL_REJECTED', 'Withdrawal Rejected'), ('WITHDRAWAL_COMPLETED', 'Withdrawal Completed'), ('TX_REVERSED', 'Transaction Reversed'), ('TX_VERIFIED', 'Transaction Verified'), ('WALLET_ADJUSTED', 'Wallet Adjusted'), ('REPORT_EXPORTED', 'Report Exported'), ('SCHEDULED_REPORT_SENT', 'Scheduled Report Sent'), ('DEPOSIT_MANUAL_COMPLETED', 'Deposit Manually Completed'), ('SETTLEMENT_CREATED', 'Settlement Created'), ('SETTLEMENT_APPROVED', 'Settlement Approved'), ('SETTLEMENT_PAID', 'Settlement Paid'), ('JOURNAL_CREATED', 'Journal Entry Created')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='financesettlementitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
