# Generated by Django 5.2.10 on 2026-05-31 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0066_userwithdrawal_email_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(choices=[('home_win', 'Home Win'), ('draw', 'Draw'), ('away_win', 'Away Win'), ('home_dnb', 'Home DNB'), ('away_dnb', 'Away DNB'), ('over_1_5', 'Over 1.5'), ('under_1_5', 'Under 1.5'), ('over_2_5', 'Over 2.5'), ('under_2_5', 'Under 2.5'), ('over_3_5', 'Over 3.5'), ('under_3_5', 'Under 3.5'), ('btts_yes', 'BTTS Yes'), ('btts_no', 'BTTS No')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fixture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popular_pick', to='betting.fixture')),
            ],
            options={
                'verbose_name': 'Popular Pick',
                'verbose_name_plural': 'Popular Picks',
                'ordering': ('sort_order', '-created_at'),
            },
        ),
    ]
