# Generated by Django 5.2.10 on 2026-06-01 07:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0067_popular_picks'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('bank_name', models.CharField(blank=True, default='', max_length=255)),
                ('account_name', models.CharField(blank=True, default='', max_length=255)),
                ('account_number', models.CharField(blank=True, default='', max_length=50)),
                ('requested_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('transaction_reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('withdrawal_status', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('event', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], db_index=True, max_length=20)),
                ('is_admin_copy', models.BooleanField(db_index=True, default=False)),
                ('email_subject', models.CharField(blank=True, default='', max_length=255)),
                ('email_to', models.TextField(blank=True, default='')),
                ('email_cc', models.TextField(blank=True, default='')),
                ('email_bcc', models.TextField(blank=True, default='')),
                ('email_body_text', models.TextField(blank=True, default='')),
                ('email_body_html', models.TextField(blank=True, default='')),
                ('email_sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('email_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_reports', to=settings.AUTH_USER_MODEL)),
                ('withdrawal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_entries', to='betting.userwithdrawal')),
            ],
            options={
                'verbose_name': 'Withdrawal Report',
                'verbose_name_plural': 'Withdrawal Reports',
                'ordering': ('-created_at',),
                'unique_together': {('withdrawal', 'event', 'is_admin_copy')},
            },
        ),
    ]
