# Generated by Django 5.2.10 on 2026-06-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0068_withdrawal_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='require_commission_recall_approval',
            field=models.BooleanField(default=False, help_text='If enabled, Account User commission recalls require Admin approval before reversal occurs.'),
        ),
    ]
