# Generated by Django 5.2.10 on 2026-06-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0069_siteconfiguration_require_commission_recall_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('bet_placement', 'Bet Placement'), ('bet_payout', 'Bet Payout'), ('commission_payout', 'Commission Payout'), ('commission_recall_debit', 'Commission Recall Debit'), ('commission_recall_credit', 'Commission Recall Credit'), ('wallet_transfer_out', 'Wallet Transfer Out'), ('wallet_transfer_in', 'Wallet Transfer In'), ('bonus', 'Bonus'), ('ticket_deletion_refund', 'Ticket Deletion Refund'), ('withdrawal_refund', 'Withdrawal Refund'), ('account_user_debit', 'Account User Debit'), ('account_user_credit', 'Account User Credit')], max_length=50),
        ),
    ]
