# Generated by Django 5.2.10 on 2026-06-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0070_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_global_cashier_voiding',
            field=models.BooleanField(default=False, help_text='If enabled, all cashiers can submit ticket void requests. If disabled, agent-level cashier permissions apply.', verbose_name='Enable Ticket Voiding For All Cashiers'),
        ),
    ]
