# Generated by Django 5.2.10 on 2026-06-12 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0079_agenttransferlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLockAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_reason', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(choices=[('locked', 'Locked'), ('appeal_submitted', 'Appeal Submitted'), ('appeal_approved', 'Appeal Approved'), ('appeal_rejected', 'Appeal Rejected'), ('unlocked', 'Unlocked')], db_index=True, max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('appealed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_lock_appeals_logged', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_lock_events_created', to=settings.AUTH_USER_MODEL)),
                ('locked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_lock_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_lock_reviews_logged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Lock Audit Log',
                'verbose_name_plural': 'Account Lock Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AccountUnlockAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal_reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('admin_comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('appealed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_unlock_appeals_submitted', to=settings.AUTH_USER_MODEL)),
                ('locked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_unlock_appeals_received', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_unlock_appeals_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_unlock_appeals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Unlock Appeal',
                'verbose_name_plural': 'Account Unlock Appeals',
                'ordering': ['-created_at'],
            },
        ),
    ]
