# Generated by Django 5.2.10 on 2026-06-13 19:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0080_accountlockauditlog_accountunlockappeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='crm_failed_deposit_repeat_threshold',
            field=models.PositiveIntegerField(default=3, help_text='Minimum number of failed deposits before a user is flagged as a repeated failed depositor.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='crm_large_deposit_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('100000.00'), help_text='Deposit amount at or above this threshold is treated as a large deposit for CRM monitoring.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.CreateModel(
            name='BulkMessageCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', max_length=160)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('in_app', 'In-App Notification')], db_index=True, max_length=20)),
                ('target_group', models.CharField(choices=[('all_users', 'All Users'), ('all_agents', 'All Agents'), ('all_super_agents', 'All Super Agents'), ('all_retail_managers', 'All Retail Managers'), ('specific_agents', 'Specific Agents'), ('dormant_users', 'Dormant Users'), ('high_value_users', 'High Value Users'), ('recent_registrations', 'Recent Registrations'), ('failed_deposit_users', 'Users With Failed Deposits'), ('pending_withdrawal_users', 'Users With Pending Withdrawals'), ('custom_users', 'Custom Users')], db_index=True, max_length=40)),
                ('schedule_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('recurring_pattern', models.CharField(choices=[('none', 'One-off'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], db_index=True, default='none', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('sent', 'Sent'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('target_user_ids', models.JSONField(blank=True, default=list)),
                ('target_agent_ids', models.JSONField(blank=True, default=list)),
                ('filter_snapshot', models.JSONField(blank=True, default=dict)),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('opened_count', models.PositiveIntegerField(default=0)),
                ('clicked_count', models.PositiveIntegerField(default=0)),
                ('conversion_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_message_campaigns_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkMessageDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('in_app', 'In-App Notification')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('converted', 'Converted')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='betting.bulkmessagecampaign')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_message_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('promotions', 'Promotions'), ('bonus_offers', 'Bonus Offers'), ('account_alerts', 'Account Alerts'), ('kyc_reminders', 'KYC Reminders'), ('deposit_reminders', 'Deposit Reminders'), ('dormancy_reminders', 'Dormancy Reminders'), ('commission_updates', 'Commission Updates')], db_index=True, max_length=30)),
                ('subject', models.CharField(blank=True, default='', max_length=160)),
                ('message', models.TextField()),
                ('default_channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('in_app', 'In-App Notification')], default='in_app', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_message_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='bulkmessagecampaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='betting.bulkmessagetemplate'),
        ),
        migrations.CreateModel(
            name='CustomerComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('ticket', 'Ticket Complaints'), ('wallet', 'Wallet Complaints'), ('withdrawal', 'Withdrawal Complaints'), ('deposit', 'Deposit Complaints'), ('commission', 'Commission Complaints')], db_index=True, max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to=models.Q(('user_type', 'crm'), ('user_type', 'admin'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customer_complaints', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_complaints', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CRMOpsAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('dormant_accounts', 'Dormant Accounts'), ('complaints', 'Complaints'), ('deposit_monitoring', 'Deposit Monitoring'), ('agent_performance', 'Agent Performance'), ('user_activation', 'User Activation'), ('bulk_messaging', 'Bulk Messaging')], db_index=True, max_length=40)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_ops_actions', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='betting.bulkmessagecampaign')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_ops_targets', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_ops_audit_logs', to='betting.transaction')),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='betting.customercomplaint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerComplaintNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('is_internal', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_complaint_notes', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='betting.customercomplaint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
