# Generated by Django 5.2.10 on 2026-06-16 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0081_siteconfiguration_crm_failed_deposit_repeat_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('action_type', models.CharField(choices=[('DUPLICATE_EMAIL_ASSIGNED', 'Duplicate Email Assigned'), ('DUPLICATE_EMAIL_UPDATED', 'Duplicate Email Updated'), ('CASHIER_EMAIL_SYNCHRONIZED', 'Cashier Email Synchronized'), ('AGENT_CASHIER_EMAIL_SYNC_TRIGGERED', 'Agent Cashier Email Sync Triggered')], db_index=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='cashierregistrationrequest',
            name='unique_cashier_request_email',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddField(
            model_name='emailauditlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_email_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailauditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
