# Generated by Django 5.2.10 on 2026-06-18 22:03

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0082_emailauditlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='account_locked_due_to_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='account_unlocked_after_settlement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='approval_level',
            field=models.CharField(choices=[('super_agent', 'Super Agent'), ('admin', 'Admin')], default='super_agent', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('agent_overdraft', 'Agent Overdraft'), ('super_agent_overdraft', 'Super Agent Overdraft'), ('manual_overdraft', 'Manual Overdraft')], default='agent_overdraft', max_length=30),
        ),
        migrations.AddField(
            model_name='loan',
            name='manual_assignment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='qualification_deposit_volume',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='qualification_ticket_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='qualified_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='loan',
            name='repaid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='request_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='loan',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='workflow_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='loan_application_day',
            field=models.CharField(default='friday', help_text='Day of week when overdraft applications open.', max_length=12),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='loan_application_time',
            field=models.TimeField(default=datetime.time(16, 0), help_text='Time when overdraft applications open.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='loan_min_deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text='Minimum successful gateway deposit volume required to qualify for an overdraft request.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='loan_min_ticket_count',
            field=models.PositiveIntegerField(default=50, help_text='Minimum valid ticket count required to qualify for an overdraft request in the current commission window.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='loan_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Percentage of qualified deposits that can be requested as overdraft.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='loan_repayment_day',
            field=models.CharField(default='saturday', help_text='Day of week when overdraft repayment is due.', max_length=12),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='loan_repayment_time',
            field=models.TimeField(default=datetime.time(15, 0), help_text='Time when overdraft repayment is due.'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('overdue', 'Overdue'), ('settled', 'Settled'), ('defaulted', 'Defaulted')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='LoanAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('request_submitted', 'Request Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('manual_assigned', 'Manual Assigned'), ('repayment_received', 'Repayment Received'), ('auto_deduction', 'Automatic Deduction'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('override', 'Override'), ('loan_cleared', 'Loan Cleared')], db_index=True, max_length=30)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_audit_events', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='betting.loan')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Audit Log',
                'verbose_name_plural': 'Loan Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(choices=[('gateway_deposit', 'Gateway Deposit'), ('admin_credit', 'Admin Credit'), ('manual_settlement', 'Manual Settlement'), ('finance_credit', 'Finance Credit'), ('reconcile_credit', 'Reconciled Credit')], max_length=30)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_repayments', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='betting.loan')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_repayments_recorded', to=settings.AUTH_USER_MODEL)),
                ('source_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_repayments', to='betting.transaction')),
            ],
            options={
                'verbose_name': 'Loan Repayment',
                'verbose_name_plural': 'Loan Repayments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OverdraftWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_funded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('super_agent', models.OneToOneField(limit_choices_to={'user_type': 'super_agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='overdraft_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Overdraft Wallet',
                'verbose_name_plural': 'Overdraft Wallets',
                'ordering': ['super_agent__username', 'super_agent__email'],
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='overdraft_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funded_loans', to='betting.overdraftwallet'),
        ),
        migrations.CreateModel(
            name='OverdraftWalletLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], db_index=True, max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overdraft_wallet_actions', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overdraft_wallet_entries', to='betting.loan')),
                ('super_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overdraft_wallet_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='betting.overdraftwallet')),
            ],
            options={
                'verbose_name': 'Overdraft Wallet Ledger Entry',
                'verbose_name_plural': 'Overdraft Wallet Ledger Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
