# Generated by Django 5.2.10 on 2026-06-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0083_loan_account_locked_due_to_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
