# Generated by Django 5.2.10 on 2026-06-18 23:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0084_loan_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanauditlog',
            name='action',
            field=models.CharField(choices=[('request_submitted', 'Request Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('manual_assigned', 'Manual Assigned'), ('credit_reserved', 'Credit Reserved'), ('repayment_received', 'Repayment Received'), ('auto_deduction', 'Automatic Deduction'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('override', 'Override'), ('loan_cleared', 'Loan Cleared')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='LoanPendingCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('gateway_deposit', 'Gateway Deposit'), ('admin_credit', 'Admin Credit'), ('account_user_credit', 'Account User Credit'), ('crm_credit', 'CRM Credit'), ('finance_credit', 'Finance Credit'), ('reconcile_credit', 'Reconciled Credit')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_pending_credits', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_pending_credits_recorded', to=settings.AUTH_USER_MODEL)),
                ('source_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_pending_credits', to='betting.transaction')),
            ],
            options={
                'verbose_name': 'Loan Pending Credit',
                'verbose_name_plural': 'Loan Pending Credits',
                'ordering': ['-created_at'],
            },
        ),
    ]
