# Generated by Django 5.2.10 on 2026-06-20 17:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0085_alter_loanauditlog_action_loanpendingcredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTransactionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=120, unique=True)),
                ('reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('transaction_type', models.CharField(db_index=True, max_length=80)),
                ('source', models.CharField(db_index=True, max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_transaction_ledgers_created', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_ledgers', to='betting.betticket')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_transaction_ledgers', to='betting.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_transaction_ledgers', to=settings.AUTH_USER_MODEL)),
                ('wallet_ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_transaction_ledger', to='betting.walletledgerentry')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='bet_ttl_user_created_idx'), models.Index(fields=['user', 'transaction_type'], name='bet_ttl_user_type_idx'), models.Index(fields=['user', 'source'], name='bet_ttl_user_source_idx'), models.Index(fields=['ticket', 'created_at'], name='bet_ttl_ticket_created_idx'), models.Index(fields=['transaction', 'created_at'], name='bet_ttl_tx_created_idx')],
            },
        ),
    ]
