# Generated by Django 5.2.10 on 2026-06-22 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0087_bettingperiod_fixture_theme_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='assigned', max_length=20)),
                ('completion_report', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('assigned_to', models.ForeignKey(limit_choices_to=models.Q(('user_type', 'crm'), ('user_type', 'retail_manager'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dashboard_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Task',
                'verbose_name_plural': 'Dashboard Tasks',
                'ordering': ['status', 'due_at', '-created_at'],
            },
        ),
    ]
