# Generated by Django 5.2.10 on 2026-07-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0090_fixture_double_chance_odds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularpick',
            name='bet_type',
            field=models.CharField(choices=[('home_win', 'Home Win'), ('draw', 'Draw'), ('away_win', 'Away Win'), ('home_or_draw', 'Home Win or Draw (1X)'), ('either_team_win', 'Anybody Wins (12)'), ('away_or_draw', 'Away Win or Draw (X2)'), ('home_dnb', 'Home DNB'), ('away_dnb', 'Away DNB'), ('over_1_5', 'Over 1.5'), ('under_1_5', 'Under 1.5'), ('over_2_5', 'Over 2.5'), ('under_2_5', 'Under 2.5'), ('over_3_5', 'Over 3.5'), ('under_3_5', 'Under 3.5'), ('btts_yes', 'BTTS Yes'), ('btts_no', 'BTTS No')], max_length=50),
        ),
    ]
