# Generated by Django 5.2.10 on 2026-07-17 13:36

import betting.models
import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0092_alter_crmopsauditlog_module_crmdailyreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailDailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('branch_name', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned For Correction')], db_index=True, default='draft', max_length=20)),
                ('shops_visited', models.PositiveIntegerField(default=0)),
                ('agents_supported', models.PositiveIntegerField(default=0)),
                ('cashiers_supported', models.PositiveIntegerField(default=0)),
                ('support_calls_made', models.PositiveIntegerField(default=0)),
                ('support_calls_received', models.PositiveIntegerField(default=0)),
                ('whatsapp_followups', models.PositiveIntegerField(default=0)),
                ('escalation_cases', models.PositiveIntegerField(default=0)),
                ('general_notes', models.TextField(blank=True, default='')),
                ('pending_withdrawals_reviewed', models.PositiveIntegerField(default=0)),
                ('withdrawals_resolved', models.PositiveIntegerField(default=0)),
                ('dormant_accounts_contacted', models.PositiveIntegerField(default=0)),
                ('dormant_accounts_reactivated', models.PositiveIntegerField(default=0)),
                ('agent_complaints_received', models.PositiveIntegerField(default=0)),
                ('agent_complaints_resolved', models.PositiveIntegerField(default=0)),
                ('shop_issues_identified', models.PositiveIntegerField(default=0)),
                ('shop_issues_resolved', models.PositiveIntegerField(default=0)),
                ('new_agents_onboarded', models.PositiveIntegerField(default=0)),
                ('training_sessions_conducted', models.PositiveIntegerField(default=0)),
                ('compliance_checks_completed', models.PositiveIntegerField(default=0)),
                ('terminals_checked', models.PositiveIntegerField(default=0)),
                ('terminals_fixed', models.PositiveIntegerField(default=0)),
                ('stock_requests_handled', models.PositiveIntegerField(default=0)),
                ('marketing_support_requests', models.PositiveIntegerField(default=0)),
                ('field_visit_notes', models.TextField(blank=True, default='')),
                ('total_stake_influenced', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('estimated_revenue_influenced', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('commissions_followed_up', models.PositiveIntegerField(default=0)),
                ('fraud_cases_flagged', models.PositiveIntegerField(default=0)),
                ('retention_actions_taken', models.PositiveIntegerField(default=0)),
                ('customers_assisted_to_bet', models.PositiveIntegerField(default=0)),
                ('high_value_players_contacted', models.PositiveIntegerField(default=0)),
                ('inactive_shops_reactivated', models.PositiveIntegerField(default=0)),
                ('positive_feedback', models.TextField(blank=True, default='')),
                ('negative_feedback', models.TextField(blank=True, default='')),
                ('recommendations', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='')),
                ('support_resolution_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('reactivation_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('field_visit_completion_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('training_completion_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('overall_productivity_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('browser_information', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_daily_reports_created', to=settings.AUTH_USER_MODEL)),
                ('retail_manager', models.ForeignKey(limit_choices_to={'user_type': 'retail_manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='retail_daily_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_daily_reports_reviewed', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_daily_reports_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retail Daily Report',
                'verbose_name_plural': 'Retail Daily Reports',
                'ordering': ['-report_date', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RetailChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.CharField(max_length=255)),
                ('impact', models.TextField(blank=True, default='')),
                ('action_taken', models.TextField(blank=True, default='')),
                ('current_status', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_rows', to='betting.retaildailyreport')),
            ],
            options={
                'verbose_name': 'Retail Challenge',
                'verbose_name_plural': 'Retail Challenges',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RetailCampaignPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=180)),
                ('campaign_type', models.CharField(max_length=120)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('field_visit', 'Field Visit')], max_length=30)),
                ('target_count', models.PositiveIntegerField(default=0)),
                ('responses', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_rows', to='betting.retaildailyreport')),
            ],
            options={
                'verbose_name': 'Retail Campaign Performance',
                'verbose_name_plural': 'Retail Campaign Performance Rows',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RetailAdminComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('comment', 'Comment'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned For Correction')], db_index=True, default='comment', max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_daily_report_comments', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_comments', to='betting.retaildailyreport')),
            ],
            options={
                'verbose_name': 'Retail Daily Report Admin Comment',
                'verbose_name_plural': 'Retail Daily Report Admin Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetailNextDayTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('expected_outcome', models.TextField(blank=True, default='')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_day_tasks', to='betting.retaildailyreport')),
            ],
            options={
                'verbose_name': 'Retail Next Day Task',
                'verbose_name_plural': 'Retail Next Day Tasks',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RetailReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=betting.models.retail_report_attachment_upload_to, validators=[betting.models.validate_crm_report_attachment_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xlsx', 'xls', 'doc', 'docx', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'mp3', 'wav', 'ogg', 'm4a', 'aac', 'webm'])])),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='betting.retaildailyreport')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_report_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retail Report Attachment',
                'verbose_name_plural': 'Retail Report Attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetailSupportActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_or_agent', models.CharField(max_length=180)),
                ('issue', models.TextField()),
                ('escalated_to', models.CharField(blank=True, default='', max_length=160)),
                ('status', models.CharField(blank=True, default='Open', max_length=80)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_rows', to='betting.retaildailyreport')),
            ],
            options={
                'verbose_name': 'Retail Support Activity',
                'verbose_name_plural': 'Retail Support Activities',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='retaildailyreport',
            constraint=models.UniqueConstraint(fields=('retail_manager', 'report_date'), name='uniq_retail_daily_report_manager_date'),
        ),
    ]
