# Generated by Django 5.2.10 on 2026-07-29 14:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0093_retaildailyreport_retailchallenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='betticket',
            name='cashout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='betticket',
            name='cashout_company_margin_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='betticket',
            name='cashout_completed_odds',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='betticket',
            name='cashout_original_odds',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='betticket',
            name='cashout_processed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='betticket',
            name='cashout_processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashouts_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='betticket',
            name='cashout_progress_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='betticket',
            name='cashout_reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='betticket',
            name='cashout_settings_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='betticket',
            name='cashout_strategy',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('bet_placement', 'Bet Placement'), ('bet_payout', 'Bet Payout'), ('bet_cashout', 'Bet Cash Out'), ('commission_payout', 'Commission Payout'), ('commission_recall_debit', 'Commission Recall Debit'), ('commission_recall_credit', 'Commission Recall Credit'), ('wallet_transfer_out', 'Wallet Transfer Out'), ('wallet_transfer_in', 'Wallet Transfer In'), ('bonus', 'Bonus'), ('ticket_deletion_refund', 'Ticket Deletion Refund'), ('withdrawal_refund', 'Withdrawal Refund'), ('account_user_debit', 'Account User Debit'), ('account_user_credit', 'Account User Credit')], max_length=50),
        ),
        migrations.CreateModel(
            name='BetTicketCashOut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=120, unique=True)),
                ('ticket_type', models.CharField(blank=True, default='', max_length=20)),
                ('ticket_status', models.CharField(blank=True, default='', max_length=20)),
                ('stake_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('potential_win', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('original_odds', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=16)),
                ('completed_odds', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=16)),
                ('progress_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6)),
                ('company_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('cashout_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('calculation_strategy', models.CharField(blank=True, default='', max_length=40)),
                ('formula_version', models.CharField(blank=True, default='v1', max_length=20)),
                ('settings_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='completed', max_length=20)),
                ('processed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashouts_as_agent', to=settings.AUTH_USER_MODEL)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashouts_as_cashier', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashouts_processed_by', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashout', to='betting.betticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-processed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CashOutAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('message', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashout_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('cashout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='betting.betticketcashout')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashout_audit_logs', to='betting.betticket')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CashOutSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enable_cash_out', models.BooleanField(default=False)),
                ('enable_cash_out_nap', models.BooleanField(default=True)),
                ('enable_cash_out_permutation', models.BooleanField(default=True)),
                ('enable_full_cash_out', models.BooleanField(default=True)),
                ('enable_partial_cash_out', models.BooleanField(default=False)),
                ('strategy', models.CharField(choices=[('accumulated_odds', 'Accumulated Odds (Default)')], default='accumulated_odds', max_length=40)),
                ('company_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('minimum_stake_eligible', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('maximum_stake_eligible', models.DecimalField(decimal_places=2, default=Decimal('100000000.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('minimum_cash_out_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('maximum_cash_out_amount', models.DecimalField(decimal_places=2, default=Decimal('100000000.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('availability', models.CharField(choices=[('before_first_event', 'Only before first event starts'), ('in_progress', 'While events are in progress')], default='in_progress', max_length=40)),
                ('close_when_dead', models.BooleanField(default=True)),
                ('close_after_last_remaining_fixture_starts', models.BooleanField(default=False)),
                ('close_after_last_fixture_finishes', models.BooleanField(default=False)),
                ('manually_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cashout_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
