# Generated by Django 5.2.10 on 2026-07-30 06:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0094_betticket_cashout_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashoutsettings',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='cashoutsettings',
            name='close_after_last_fixture_finishes',
        ),
        migrations.RemoveField(
            model_name='cashoutsettings',
            name='close_after_last_remaining_fixture_starts',
        ),
        migrations.RemoveField(
            model_name='cashoutsettings',
            name='close_when_dead',
        ),
        migrations.RemoveField(
            model_name='cashoutsettings',
            name='company_margin_percent',
        ),
        migrations.RemoveField(
            model_name='cashoutsettings',
            name='enable_full_cash_out',
        ),
        migrations.RemoveField(
            model_name='cashoutsettings',
            name='enable_partial_cash_out',
        ),
        migrations.RemoveField(
            model_name='cashoutsettings',
            name='strategy',
        ),
        migrations.AddField(
            model_name='betticketcashout',
            name='charge_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='betticketcashout',
            name='charge_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='betticketcashout',
            name='losing_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='betticketcashout',
            name='offer_percent_of_potential',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='betticketcashout',
            name='pending_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='betticketcashout',
            name='settled_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='betticketcashout',
            name='winning_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cashoutsettings',
            name='cashout_percent_1_win',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='cashoutsettings',
            name='cashout_percent_2_win',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='cashoutsettings',
            name='cashout_percent_3_win',
            field=models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='cashoutsettings',
            name='cashout_percent_4_win',
            field=models.DecimalField(decimal_places=2, default=Decimal('80.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='cashoutsettings',
            name='cashout_percent_last_event_remaining',
            field=models.DecimalField(decimal_places=2, default=Decimal('90.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='cashoutsettings',
            name='charge_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='cashoutsettings',
            name='disable_cash_out_during_live_events',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cashoutsettings',
            name='enable_pre_match_cash_out',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cashoutsettings',
            name='fixed_charge_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='cashoutsettings',
            name='percentage_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
