# Generated by Django 5.2.10 on 2026-07-30 08:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0095_remove_cashoutsettings_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashoutsettings',
            name='cashout_percent_1_win',
        ),
        migrations.RemoveField(
            model_name='cashoutsettings',
            name='cashout_percent_2_win',
        ),
        migrations.RemoveField(
            model_name='cashoutsettings',
            name='cashout_percent_3_win',
        ),
        migrations.RemoveField(
            model_name='cashoutsettings',
            name='cashout_percent_4_win',
        ),
        migrations.RemoveField(
            model_name='cashoutsettings',
            name='cashout_percent_last_event_remaining',
        ),
        migrations.AddField(
            model_name='betticketcashout',
            name='remaining_odds',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=16),
        ),
        migrations.AddField(
            model_name='betticketcashout',
            name='risk_discount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=8),
        ),
        migrations.AddField(
            model_name='betticketcashout',
            name='risk_multiplier_used',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=8),
        ),
        migrations.AddField(
            model_name='betticketcashout',
            name='won_odds',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=16),
        ),
        migrations.AddField(
            model_name='cashoutsettings',
            name='company_margin_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='cashoutsettings',
            name='enable_full_cash_out',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cashoutsettings',
            name='enable_partial_cash_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashoutsettings',
            name='risk_multiplier',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0500'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
        ),
    ]
