# Generated by Django 5.2.10 on 2026-08-04 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0097_remove_cashoutsettings_disable_cash_out_during_live_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewaySettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enable_paystack', models.BooleanField(default=True)),
                ('enable_monnify', models.BooleanField(default=True)),
                ('enable_kora', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payment_gateway_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
