# Generated by Django 5.2.10 on 2026-09-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0103_unique_completed_bet_payout_per_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='deposit_failed_notification_emails',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of email addresses that should receive an email notification whenever a deposit fails (status=failed). Leave blank to use the default admin/finance/superuser auto-discovery list.', verbose_name='Deposit Failed — Admin Notifications'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='deposit_initiated_notification_emails',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of email addresses that should receive an email notification whenever a user initiates a deposit (transaction_type=deposit, status=pending). Leave blank to use the default admin/finance/superuser auto-discovery list.', verbose_name='Deposit Initiated (Pending) — Admin Notifications'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='deposit_successful_notification_emails',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of email addresses that should receive an email notification whenever a deposit is confirmed successful (status=completed). Leave blank to use the default admin/finance/superuser auto-discovery list.', verbose_name='Deposit Successful (Completed) — Admin Notifications'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stuck_deposit_alert_notification_emails',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of email addresses that should receive an email notification when a deposit has been pending for longer than the reconciliation threshold (default 30 minutes). Leave blank to use the existing auto-discovered list (superuser/admin/finance).', verbose_name='Stuck Pending Deposit Alerts — Admin Notifications'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='withdrawal_approved_notification_emails',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of email addresses that should receive an email notification whenever a withdrawal is approved or payout completed successfully. Leave blank to use the existing auto-discovered list.', verbose_name='Withdrawal Approved or Completed — Admin Notifications'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='withdrawal_initiated_notification_emails',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of email addresses that should receive an email notification whenever a user submits a withdrawal request. Leave blank to use the existing auto-discovered list (superuser/admin/finance/account_user + WITHDRAWAL_ADMIN_EMAILS env).', verbose_name='Withdrawal Requested (Pending) — Admin Notifications'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='withdrawal_rejected_notification_emails',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of email addresses that should receive an email notification whenever a withdrawal is rejected. Leave blank to use the existing auto-discovered list.', verbose_name='Withdrawal Rejected — Admin Notifications'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='email_failed_admin_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='For deposit: admin "failed" email sent at', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='email_failed_user_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='For deposit: user "failed" email sent at', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='email_initiated_admin_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='For deposit: admin "pending initiated" email sent at', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='email_initiated_user_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='For deposit: user "pending initiated" email sent at', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='email_successful_admin_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='For deposit: admin "completed/successful" email sent at', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='email_successful_user_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='For deposit: user "completed/successful" email sent at', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='last_email_error',
            field=models.TextField(blank=True, default='', help_text='Last email send error message (for deposit notifications)'),
        ),
    ]
