# Generated by Django 5.2.10 on 2026-09-05 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0104_add_notification_email_config'),
        ('commission', '0008_commissionperiod_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='commission_related_period',
            field=models.ForeignKey(blank=True, help_text='For commission_payout tx type: links to the CommissionPeriod this payment settles. Used in DB partial unique index to prevent double-paying the same agent+period.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_period_transactions', to='commission.commissionperiod'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'completed'), ('transaction_type', 'commission_payout')), fields=('target_user', 'commission_related_period'), name='unique_completed_commission_payout_per_agent_period', violation_error_code='duplicate_commission_payout', violation_error_message='A completed commission payout already exists for this agent and commission period.'),
        ),
    ]
