# Generated by Django 5.2.10 on 2026-09-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0105_transaction_commission_related_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bettinglimitauditlog',
            name='action_type',
            field=models.CharField(choices=[('GLOBAL_UPDATE', 'Global Update'), ('AGENT_UPDATE', 'Agent Update'), ('USER_UPDATE', 'User Update'), ('TICKET_REJECTED', 'Ticket Rejected'), ('TICKET_WINNING_CAPPED', 'Ticket Winning Capped')], max_length=30),
        ),
    ]
