# Generated by Django 5.2.10 on 2026-09-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0106_bettinglimitauditlog_winning_capped_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='withdrawals_pause_message',
            field=models.TextField(blank=True, default='', help_text="Enter the exact message users will see when withdrawals are paused. Be open and honest — e.g. 'Withdrawals are temporarily paused during Saturday peak processing to keep payout servers stable. Please try again after 11pm WAT. Your wallet balance is 100% safe and unaffected. Thank you for your patience!' If left blank, a generic default platform message is used.", verbose_name='Custom Pause Message (shown to users)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='withdrawals_pause_processing_delay_seconds',
            field=models.PositiveIntegerField(default=0, help_text="Optional artificial delay (0-60 seconds) between the user clicking 'Request Withdrawal' and the message appearing. During the delay the button shows the normal 'Processing...' state so the click feels like genuine financial processing before the honest message is shown. DO NOT combine with any network-error deception. Recommended values: 0 (instant) or 3-8 seconds (feels real processing). Maximum 60 seconds to avoid request timeouts.", verbose_name='Processing Delay Before Showing Message (seconds)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='withdrawals_paused',
            field=models.BooleanField(default=False, help_text="When checked, non-admin users cannot submit new withdrawal requests. The submit button shows a normal 'Processing...' indicator during the configured delay, then displays the honest custom message below (never a false network-error spinner gimmick). Admins/Finance users can still submit withdrawals. Uncheck to restore normal withdrawals.", verbose_name='Pause All New Withdrawal Requests'),
        ),
    ]
