# Generated by Django 5.2.10 on 2026-09-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0107_add_siteconfig_withdrawals_pause_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='withdraw_button_disabled',
            field=models.BooleanField(default=False, help_text="When checked, the Request Withdrawal button on the user Wallet page is disabled/hidden for all non-admin/finance users, and backend withdrawal requests are blocked (even if a user submits the request directly via AJAX / curl). Uncheck to enable withdrawals again. This is DIFFERENT from 'Pause All New Withdrawal Requests' above (which still shows the button + shows an honest message after click / artificial delay). Use this checkbox for hard OFF / kill switch emergencies. Admin/Finance/superuser accounts bypass this setting for operational testing.", verbose_name='Disable withdrawal button on user wallet'),
        ),
    ]
