# Generated by Django 5.2.10 on 2026-09-30 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0108_siteconfiguration_withdraw_button_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAgentTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('new_master_agent', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'master_agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='super_agent_transfer_logs_as_new_ma', to=settings.AUTH_USER_MODEL)),
                ('old_master_agent', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'master_agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='super_agent_transfer_logs_as_old_ma', to=settings.AUTH_USER_MODEL)),
                ('super_agent', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'super_agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='super_agent_transfer_logs', to=settings.AUTH_USER_MODEL)),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='super_agent_transfer_logs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Super Agent Transfer Log',
                'verbose_name_plural': 'Super Agent Transfer Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
