# Generated by Django 5.2.10 on 2026-01-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymetricsnapshot',
            name='date',
            field=models.DateField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dailymetricsnapshot',
            name='total_stake_volume',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=15),
        ),
    ]
