# Generated by Django 5.2.10 on 2026-01-26 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uip', '0002_alter_dailymetricsnapshot_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIPDashboardLink',
            fields=[
            ],
            options={
                'verbose_name': 'UIP Dashboard',
                'verbose_name_plural': 'Open UIP Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('uip.dailymetricsnapshot',),
        ),
    ]
