# Generated by Django 5.2.10 on 2026-05-17 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uip', '0003_uipdashboardlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertAffectedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('risk_score', models.IntegerField(default=0)),
                ('last_activity_time', models.DateTimeField(blank=True, null=True)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_deposits', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_bets_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Affected User',
                'verbose_name_plural': 'Alert Affected Users',
            },
        ),
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('multi_account', 'Multi-Account Detected'), ('bonus_abuse', 'Bonus Abuse Suspected'), ('suspicious_betting', 'Suspicious Betting Pattern'), ('high_value_bet', 'High Value Bet'), ('vpn_usage', 'VPN Usage Detected'), ('shared_device', 'Shared Device Detected'), ('payment_fraud', 'Payment Method Fraud')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'LOW'), ('medium', 'MEDIUM'), ('high', 'HIGH'), ('critical', 'CRITICAL')], default='medium', max_length=20)),
                ('description', models.TextField()),
                ('detection_source', models.CharField(default='system', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_investigation', 'Under Investigation'), ('resolved_safe', 'Resolved (Safe)'), ('resolved_fraud', 'Resolved (Fraud)'), ('escalated', 'Escalated')], db_index=True, default='pending', max_length=30)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('related_ips', models.JSONField(blank=True, default=list)),
                ('related_devices', models.JSONField(blank=True, default=list)),
                ('affected_users', models.ManyToManyField(related_name='fraud_alerts', through='uip.AlertAffectedUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fraud Alert',
                'verbose_name_plural': 'Fraud Alerts',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='alertaffecteduser',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_user_details', to='uip.fraudalert'),
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='uip.fraudalert')),
            ],
            options={
                'verbose_name': 'Admin Action Log',
                'verbose_name_plural': 'Admin Action Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_case', to='uip.fraudalert')),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='alertaffecteduser',
            unique_together={('alert', 'user')},
        ),
    ]
