# Generated by Django 5.2.10 on 2026-06-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('DEPOSIT_SUCCESS', 'Deposit Successful'), ('WITHDRAWAL_APPROVED', 'Withdrawal Approved'), ('WITHDRAWAL_REJECTED', 'Withdrawal Rejected'), ('BONUS_AWARDED', 'Bonus Awarded'), ('TICKET_SETTLED', 'Ticket Settled'), ('EVENT_SUSPENDED', 'Event Suspended'), ('EVENT_ABANDONED', 'Event Abandoned'), ('FIXTURE_POSTPONED', 'Fixture Postponed'), ('ODDS_CHANGED', 'Odds Changed'), ('TICKET_VOIDED', 'Ticket Voided'), ('SYSTEM_ANNOUNCEMENT', 'System Announcement'), ('RISK_ALERT', 'Risk Alert'), ('DEPOSIT_REMINDER', 'Deposit Reminder'), ('LOAN_REQUEST_SUBMITTED', 'Loan Request Submitted'), ('LOAN_REQUEST_PENDING_REVIEW', 'Loan Request Pending Review'), ('LOAN_APPROVED', 'Loan Approved'), ('LOAN_REJECTED', 'Loan Rejected'), ('LOAN_REPAYMENT_RECEIVED', 'Loan Repayment Received'), ('LOAN_ACCOUNT_LOCKED', 'Loan Account Locked'), ('LOAN_ACCOUNT_UNLOCKED', 'Loan Account Unlocked'), ('LOAN_CLEARED', 'Loan Cleared'), ('LOAN_MANUAL_ASSIGNED', 'Manual Loan Assigned')], db_index=True, max_length=40),
        ),
    ]
